---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_prompt: yes
configure_python: yes
configure_vim: yes
configure_fonts: yes
configure_macos: yes
mas_installed_apps: yes

# Install dotfiles from a git repo
dotfiles_repo: https://github.com/bmacauley/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bashrc
  - .bash_prompt
  - .editorconfig
  - .functions
  - .gitconfig
  - .gitignore
  - .hushlogin
  - .macos
  - .paths
  - .tmux.conf
  - .zprofile
  - .zshrc
  - .zsh_prompt


# Install/upgrade homebrew packages/taps/casks
homebrew_upgrade_all_packages: yes

homebrew_uninstalled_packages: []

homebrew_installed_packages:
  ## Cloud Tools ##
  - awscli
  - aws-sam-cli
  - aws-shell
  - consul
  - docker
  - docker-clean
  - docker-compose
  - heroku
  - heroku-toolbelt
  - minikube
  - nomad
  - packer
  - packer-completion
  - s3cmd
  - terragrunt
  - terraform-docs
  - tfenv
  - vagrant
  - vagrant-completion
  - vault
  ## Git Tools ##
  - act
  - gist
  - git
  - git-crypt
  - hub
  - tig
  ## Unix Tools ##
  - bash
  - bash-completion
  - battery
  - brew-cask-completion
  - bundler-completion
  - cloc
  - curl
  - direnv
  - htop-osx
  - gpg
  - gpg2
  - libevent
  - libffi
  - libvterm
  - libxml2
  - libyaml
  - jq
  - nmap
  - openssl
  - tmux
  - tree
  - wget
  - wrk
  ## MacOS Tools ##
  - launchctl-completion
  - mas
  - openvpn
  - zsh-completions
  - zenith

  # - autoconf
  # - autojump
  # - awsebcli
  # - bazel java issues
  # - bfg
  # - buck
  # - cowsay
  # - cookiecutter
  # - ctags
  # - docker-gen
  # - docker-machine
  # - docker-swarm
  # - duti
  # - enca
  # - fasd
  # - fish
  # - freetds
  # - gdbm
  # - geoip
  # - gettext
  # - git-flow
  # - github-release
  # - git-subrepo
  # - gitup
  # - glide
  # - go
  # - gradle
  # - gradle-completion
  # - httpie
  # - hugo
  # - ipcalc
  # - iperf
  # - k3d
  # - derailed/k9s/k9s
  # - kind
  # - kitchen-completion
  # - kops
  # - lynis
  # - macvim
  # - maven
  # - mcrypt
  # - md5sha1sum
  # - mobile-shell
  # - mtr
  # - multitail
  # - mysql
  # - node
  # - npm
  # - nvm
  # - nginx
  # - osquery
  # - p7zip
  # - packer
  # - pandoc
  # - parallel
  # - pgcli
  # - pip-completion
  # - postgresql
  # - pup
  # - pv
  # - pyenv
  # - pyenv-virtualenv
  # - pyenv-virtualenvwrapper
  # - python
  # - python@2
  # - rails-completion
  # - rake-completion
  # - ruby-completion
  # - rancher-cli
  # - rancher-compose
  # - rbenv
  # - readline
  # - reattach-to-user-namespace
  # - redis
  # - ruby
  # - saltstack
  # - scons
  # - serverless
  # - sshuttle
  # - spark
  # - sqlite
  # - ssh-copy-id
  # - stunnel
  # - tccutil
  # - terraform
  # - the_platinum_searcher
  # - the_silver_searcher
  # - unixodbc
  # - udptunnel
  # - vim
  # - wireguard-go
  # - wireguard-tools
  # - zeromq
  # - z
  # - zsh

homebrew_taps:
  - homebrew/core
  # - caskroom/cask
  - Goles/battery
  - facebook/fb
  - aws/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  ## Development Tools ##
  - brave-browser
  - docker
  - discord
  - firefox
  - github
  - google-chrome
  - gpg-suite
  - keybase
  - microsoft-teams
  - postman
  - virtualbox
  - visual-studio-code
  - zoom

  # - alfred
  # - amazon-workdocs
  # - amazon-workspaces
  # - atom
  # - caffeine
  # - charles
  # - clipy
  # - coconutbattery
  # - cyberduck
  # - dropbox
  # - fantastical
  # - flux
  # - gas-mask
  # - gitter
  # - gitkraken
  # - google-photos-backup-and-sync
  # - google-hangouts
  # - handbrake
  # - intellij-idea
  # - iterm2
  # - istat-menus
  # - java
  # - jetbrains-toolbox
  # - jump
  # - joinme
  # - keepassx
  # - kitematic
  # - kindle
  # - limechat
  # - omnigraffle
  # - outline-manager
  # - pgadmin4
  # - postico
  # - powershell
  # - pycharm
  # - sequel-pro
  # - shadowsocks-libev
  # - shadowsocksx
  # - shadowsocksx-ng
  # - skitch
  # - slack
  # - sourcetree
  # - sublime-text
  # - tomighty
  # - transmit
  # - tunnelblick
  # - vagrant
  # - vagrant-manager
  # - wifi-explorer
  # - vlc

# Prompt config
zsh_git_prompt_repo: https://github.com/bmacauley/zsh-git-prompt.git
zsh_git_prompt_repo_accept_hostkey: yes

# Powerline fonts
powerline_fonts_repo: https://github.com/powerline/fonts.git
powerline_fonts_repo_version: 2015-12-04
powerline_fonts_repo_accept_hostkey: yes

# Install/Update Mac App store apps using MAS
mas_installed_app_ids:
      - 497799835   # Xcode
      - 408981434   # iMovie
      - 409183694   # keynote
      - 1116599239  # NordVPN IKE - Unlimited VPN
      - 1475387142  # Tailscale
      - 1333542190  # 1Password
      - 972572731   # MoneyPro
      - 431748264   # PluralSight
      - 803453959   # Slack
      - 1147396723  # Whatsapp Desktop
      - 1153157709  # SpeedTest
      - 1559269364  # Notion
      - 409201541   # Pages
      - 462054704   # Word
      - 462058435   # Excel
      - 462062816   # Powerpoint
      - 409203825   # Numbers

      # - 1142578753  # OmniGraffle 7 (purchase)
      # - 824183456 # Affinity Photo (purchase)
      # - 405399194 # Kindle
      # - 824171161 # Affinity Designer (purchase)
      # - 407963104 # Pixelmator (purchase)
      # - 937984704 # Amphetamine
      # - 524141863 # Jump Desktop (purchase)
      # - 1295203466 # Microsoft Remote Desktop v10
      # - 441258766 # Magnet (purchase)
      # - 406056744 # Evernote