---
downloads: ~/.ansible-downloads/

configure_sudoers: no

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: yes
# dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
# dotfiles_files:
#   - .bash_profile
#   - .gitconfig
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc


homebrew_installed_packages:
  - ack
  - awscli
  - aws-shell 
  # - ansible # Installed via Pip.
  - autoconf
  - bash 
  - bash-completion
  - battery
  - cowsay
  - ctags
  - curl
  - docker
  - docker-clean
  - docker-compose
  - docker-gen
  - docker-machine
  - enca
  - fish
  - freetds
  - gdbm
  - geoip
  - gettext
  - git
  - git-crypt
  - git-flow
  - git-subrepo
  - gitup
  - go
  - gpg
  - gradle
  - hub
  - heroku
  - heroku-toolbelt
  - htop-osx
  - httpie
  - hugo
  - ipcalc
  - iperf
  - jq
  - keychain
  - libevent
  - libffi
  - libvterm
  - libxml2
  - libyaml
  - macvim
  - maven
  - mcrypt
  - md5sha1sum
  - mercurial
  - mobile-shell
  - mtr
  - multitail
  - mysql
  - nmap
  - node
  - npm
  - nvm
  - nginx
  - mas
  - openssl
  - openvpn
  - p7zip
  - packer
  - pandoc
  - parallel
  - postgresql
  - pup
  - pv
  - python
  - python3
  - rancher-cli
  - rancher-compose
  - rbenv
  - readline
  - reattach-to-user-namespace
  - redis
  - ruby
  - s3cmd
  - saltstack
  - scons
  - spark
  - sqlite
  - ssh-copy-id
  - tccutil
  - terraform
  - the_platinum_searcher
  - the_silver_searcher
  - tig
  - tmux
  - tree
  - unixodbc
  - vim
  - wget
  - wrk
  - zeromq
  - zsh
 

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions
  - homebrew/completions
  - Goles/battery

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  #- amazon-drive
  #- airmail-beta
  - alfred
  - amazon-workdocs
  - amazon-workspaces
  - atom
  - caffeine
  - charles
  - clipmenu
  - coconutbattery
  - cyberduck
  - docker
  - dropbox
  - fantastical
  #- fing
  - firefox
  - flux
  - gas-mask
  - gitter
  - github-desktop
  - google-chrome
  - google-drive
  - google-hangouts
  # - handbrake
  - intellij-idea
  - iterm2
  - istat-menus
  - java
  - jump-desktop
  - joinme
  - kitematic
  - kindle
  # - kdiff3
  # - licecap
  - limechat
  # - yujitach-menumeters # Note: Using forked version for 10.11+ support
  # - nvalt
  - omnigraffle
  - pgadmin4
  - postico
  - postman
  - powershell
  - pycharm
  - sequel-pro
  # - skype
  - skitch
  - slack
  - sublime-text
  - tomighty
  - transmit
  - tunnelblick
  - vagrant
  - virtualbox
  - visual-studio-code
  - wifi-explorer
  # - vlc
  # 
