---
downloads: ~/.ansible-downloads/

configure_sudoers: no

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: yes
# dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
# dotfiles_files:
#   - .bash_profile
#   - .gitconfig
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc


homebrew_installed_packages:
  - ack
  - awscli
  - aws-shell 
  # - ansible # Installed via Pip.
  - autoconf
  - bash 
  - bash-completion
  - cowsay
  - ctags
  - curl
  - enca
  - fish
  - freetds
  - gdbm
  - geoip
  - gettext
  - git
  - git-crypt
  - git-encrypt
  - git-flow
  - git-subrepo
  - gitup
  - go
  - gpg
  - gradle
  - hub
  - heroku
  - heroku-toolbelt
  - htop-osx
  - httpie
  - hugo
  - ipcalc
  - iperf
  - jq
  - keychain
  - libevent
  - libffi
  - libvterm
  - libxml2
  - libyaml
  - macvim
  - maven
  - mcrypt
  - md5sha1sum
  - mercurial
  - mobile-shell
  - mtr
  - multitail
  - mysql
  - nmap
  - node
  - npm
  - nvm
  - nginx
  - openssl
  - p7zip
  - packer
  - pandoc
  - parallel
  - postgresql
  - pup
  - pv
  - python
  - python3
  - rbenv
  - readline
  - reattach-to-user-namespace
  - redis
  - ruby
  - s3cmd
  - saltstack
  - scons
  - sqlite
  - sqsh
  - ssh-copy-id
  - tccutil
  - terraform
  - the_platinum_searcher
  - the_silver_searcher
  - tig
  - tmux
  - tree
  - unixodbc
  - vim
  - wget
  - wrk
  - zeromq
 

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - docker
  # - dropbox
  # - fing
  # - firefox
  # - google-chrome
  # - handbrake
  # - kdiff3
  # - licecap
  # - limechat
  # - macvim
  # - yujitach-menumeters # Note: Using forked version for 10.11+ support
  # - nvalt
  # - sequel-pro
  # - skype
  # - skitch
  # - slack
  # - sublime-text
  # - transmit
  # - vagrant
  # - virtualbox
  # - vlc