---
- hosts: all
  connection: local

  vars_files:
      - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - ansible-role-homebrew
    - ansible-role-dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    # - include: tasks/preferences.yml
