---
- src: https://github.com/bmacauley/ansible-role-homebrew
  version: master
  name: ansible-role-homebrew

# - src: https://github.com/bmacauley/ansible-role-dotfiles
#   version: master
#   name: ansible-role-dotfiles