---
- name: Ensure that .prompt dir exists
  file:
    path: ~/.prompt
    state: directory

- name: Clone zsh-git-prompt repository .prompt directory
  git:
    repo: "{{ zsh_git_prompt_repo }}"
    dest: ~/.prompt/zsh-git-prompt
    accept_hostkey: "{{ zsh_git_prompt_repo_accept_hostkey }}"
  become: no
