---
- name: Clone Vundle repository
  git:
    repo: "{{ vundle_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}/.vim/bundle/Vundle.vim"
    accept_hostkey: "{{ vundle_repo_accept_hostkey }}"
  become: no

- name:	Install Vim modules
  command: vim -i NONE -c VundleUpdate -c quitall